### ISSUE TITLE
Method names changes in libstandalonelibwebviewchromium.so after build

### ISSUE THREAD

**Issue by avisheknath321** [ridi/chromium-aw#2]
Hi,

I am using libstandalonelibwebviewchromium.so in my android application and when I am calling a native method it throws "java.lang.UnsatisfiedLinkError: No implementation" . I have looked into this issue and found out that name of the function is different in the library. I have used  "nm -gD libstandalonelibwebviewchromium.so" command to list all the methods. For example :

method "org_chromium_base_library_1loader_LibraryLoader_registerNonMainDexJni"  changed to "Java_J_N_MIOj213u".

How to configure chromium at the build time to preserve original library method name??

Please help....

**Comment by DavinAhn** [comment]
Sorry for the late reply.

The way to rename a method is to set a [build flags](https://www.chromium.org/developers/gn-build-configuration#TOC-Faster-builds-with-no-or-minimal-symbols) or create an interface.

Build flags are not available for 32 bit ABI depending on the level. (Google Official)

The interface is to add a method that directly calls the serialized method in J.N.java.
