### ISSUE TITLE
localStorage is null

### ISSUE THREAD

**Issue by Gaubee** [ridi/chromium-aw#6]
The `sessionStorage` is work.
but `localStorage` is `null`.
![image](https://user-images.githubusercontent.com/2151644/104981486-ac013100-5a43-11eb-9ba4-2c5f5090902d.png)
How can I enable the feature?

**Comment by phamducgiam** [comment]
@Gaubee : can you tell me how to use this library. I could not find any view to use in my activity. Thanks

**Comment by DavinAhn** [comment]
@phamducgiam I'll be posting sample code sooner or later.

**Comment by DavinAhn** [comment]
@Gaubee Sorry for the late reply.
To use `localStorage`, you need to enable the relevant setting in AwSettings. See [here](https://github.com/ridi/chromium-aw/blob/master/demo/app/src/main/java/com/ridi/awdemo/WebView.kt#L46).

**Comment by DavinAhn** [comment]
@phamducgiam See [here](https://github.com/ridi/chromium-aw/tree/master/demo).
